### ISSUE TITLE
Incorrect anchor links

### ISSUE THREAD

**Issue by Huskydog9988** [emersonbottero/vitepress-plugin-search#10]
So after selecting a search item, it doesn't give the proper anchor for an item like `[thing] text` or `one 1.2`. It doesn't use the ids set by vitepress, and what I assume is happening is its incorrectly assuming them.The proper anchor in vitepress would be `thing-text` and `one-1-2` respectivly, but the search returns `[thing]text` and it won't even return the item for `one 1.2`. (There its a h3 and its returning the h2 above it.)

**Comment by emersonbottero** [comment]
you are right and should be easy to fix.. (I didn't create an example with spaces in the anchors.. )
