### ISSUE TITLE
I Can`t search for Chinese

### ISSUE THREAD

**Issue by yyrc** [emersonbottero/vitepress-plugin-search#11]
I hope to be able to search for Chinese

**Comment by emersonbottero** [comment]
Do you have an repo with an example?

**Comment by yyrc** [comment]
https://yiyu.in/

**Comment by emersonbottero** [comment]
Do you have a repo to share? Is hard to debug with only that info.

**Comment by emersonbottero** [comment]
It works if you place a space after.. , not great... I'm gonna take a look.
I'll also should handle the frontmatter portion of the docs.

**Comment by emersonbottero** [comment]
@yyrc can you share your repo with me?
there seems to be other problems but I can't reproduce.

**Comment by yyrc** [comment]
https://github.com/yyrc/test, You can test it.

**Comment by jonsam-ng** [comment]
Will this be fixed?I notice that when I search English words in Chinese articles, the search result is not correct and Chinese words are not searched.

**Comment by emersonbottero** [comment]
I tried to clone your repo but then couldn't find it.. 
can you share the repo again?

with more data the better..

**Comment by Charles7c** [comment]
> I tried to clone your repo but then couldn't find it.. can you share the repo again?
> 
> with more data the better..

You can clone my repo: https://github.com/Charles7c/charles7c.github.io.git

![本地搜索](https://user-images.githubusercontent.com/25446948/193439466-6b7113af-b915-481b-b9c5-4f1cf59bda7d.png)
![Image 4](https://user-images.githubusercontent.com/25446948/193439468-c8f3fcd0-59af-4daa-ac47-28231d80b6ea.png)

However, you need to enable `vitepress-plugin-search` in `docs/vite.config.ts`.

![image](https://user-images.githubusercontent.com/25446948/193439584-d6fc7622-74db-4f2b-83ba-e6e8b5c45976.png)

**Comment by Charles7c** [comment]
> Must add language support and make It avaiable in the plugin options https://github.com/MihaiValentin/lunr-languages

```js
var lunr = require('./lib/lunr.js');
require('./lunr.stemmer.support.js')(lunr);
require('./lunr.ru.js')(lunr);
require('./lunr.multi.js')(lunr);

var idx = lunr(function () {
  // the reason "en" does not appear above is that "en" is built in into lunr js
  this.use(lunr.multiLanguage('en', 'ru'));
  // then, the normal lunr index initialization
  // ...
});
```

How does the configuration take effect in the plug-in? :) @emersonbottero 

```ts
import { defineConfig } from 'vite'
import { SearchPlugin } from 'vitepress-plugin-search'

export default defineConfig({
  plugins: [
    SearchPlugin({
      //Add a wildcard at the end of the search
      wildcard: false,
      //The length of the result search preview item
      previewLength: 62,
    })
  ]
})
```

**Comment by emersonbottero** [comment]
I have to change my plugin based in my last comment

**Comment by ForeverSun** [comment]
Expecting

**Comment by emersonbottero** [comment]
just for reference https://github.com/vitejs/vite/issues/10486

**Comment by emersonbottero** [comment]
Just an updated..
The initial Idea of using the above link does not work, since I used lunr and those are for elasticLunr.

Due to the lack of maintenance in the lunr project  I decide to switch the index library to [flexsearch](https://github.com/nextapps-de/flexsearch)
I managed to create the library and it works great, but it fails on vitepress build to a problem in the library itself, [see my comment there](https://github.com/nextapps-de/flexsearch/issues/341)

Once this is fixed it should be possible to pass all index options in the library to the plugin.
the simplest way to set to chinese is specify [here](https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean) or just add the [cjk deafult language.](https://github.com/nextapps-de/flexsearch/blob/master/src/lang/cjk/default.js)

but we can and should improve that with an actual chinese language!
You guys could help to add the chinese language to the flexsearch library.. 
for now it should be:
- saving the default as chinese and [add the stop word](https://github.com/MihaiValentin/lunr-languages/blob/41cbd60963f03f57148043689a7c3bfe29ca837f/lunr.zh.js#L141) 
- if it does make sense add stemmer.. 
  -  stemmer is like considering drive, driving, driven to be use as alias in the search

**Comment by li-zheng-hao** [comment]
Is there an easy solution for now? to be honest I'm not familiar with any of the libraries mentioned above...

**Comment by emersonbottero** [comment]
just notice we can download the flexsearch files. 
I'll try bundle it all together with my plugin. 
if it works we would be able to configure as mention above.

**Comment by emersonbottero** [comment]
I did it.. 😁
please try adding the options as suggested above with flexsearch.

**Comment by emersonbottero** [comment]
Could Someone telle if It works?
@yyrc @Charles7c @li-zheng-hao @jonsam-ng

**Comment by Charles7c** [comment]
> Could Someone tell me if It works? @yyrc @Charles7c @li-zheng-hao @jonsam-ng

```
import { defineConfig } from 'vite'
import { SearchPlugin } from 'vitepress-plugin-search'

export default defineConfig({
  plugins: [
    SearchPlugin({
      lang: 'zh',
      encode: str => str.replace(/[\x00-\x7F]/g, "").split("")
    })
  ]
})

```

I upgraded the version to 1.0.4-alpha.15, and then looked at the link below, but didn't quite understand how to configure it, and finally it didn't work. 

1. https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean
2. https://github.com/nextapps-de/flexsearch/issues/207
3. https://github.com/alex-shpak/hugo-book/issues/327

**Comment by li-zheng-hao** [comment]
i tried same config, it only works when search one word ,like this:

![image](https://user-images.githubusercontent.com/22129824/199876536-dcde91e3-065b-4707-8f28-5a581e2c7ebc.png)

![image](https://user-images.githubusercontent.com/22129824/199876582-7390f438-5881-4158-b343-da6064c17ea4.png)



> > Could Someone tell me if It works? @yyrc @Charles7c @li-zheng-hao @jonsam-ng
> 
> ```
> import { defineConfig } from 'vite'
> import { SearchPlugin } from 'vitepress-plugin-search'
> 
> export default defineConfig({
>   plugins: [
>     SearchPlugin({
>       lang: 'zh',
>       encode: str => str.replace(/[\x00-\x7F]/g, "").split("")
>     })
>   ]
> })
> ```
> 
> I upgraded the version to 1.0.4-alpha.15, and then looked at the link below, but didn't quite understand how to configure it, and finally it didn't work.
> 
> 1. https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean
> 2. [Chinese and English at the same time? nextapps-de/flexsearch#207](https://github.com/nextapps-de/flexsearch/issues/207)
> 3. [有大佬知道搜索功能如何改为中文吗？ alex-shpak/hugo-book#327](https://github.com/alex-shpak/hugo-book/issues/327)

**Comment by emersonbottero** [comment]
It should be

{
    encode: str => str.replace(/[\x00-\x7F]/g, "").split("")
}

And you Will only find whole words..
Sto for example Will have 0 found... But stop should work. Try that plz.

**Comment by emersonbottero** [comment]
To search for partiamo there should be another settings.. I'll take a look

**Comment by li-zheng-hao** [comment]
> It should be
> 
> { encode: str => str.replace(/[\x00-\x7F]/g, "").split("") }
> 
> And you Will only find whole words.. Sto for example Will have 0 found... But stop should work. Try that plz.

no.. it not work for me...  
![image](https://user-images.githubusercontent.com/22129824/199924876-74db57d0-41e1-4102-a523-8111e54d35a5.png)

my config:
```js
import { SearchPlugin } from "vitepress-plugin-search";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [SearchPlugin({
    encode: str => str.replace(/[\x00-\x7F]/g, "").split("")
  })],
});

```

**Comment by emersonbottero** [comment]
Try both settings toguether.
```js
import { SearchPlugin } from "vitepress-plugin-search";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [SearchPlugin({
    encode: str => str.replace(/[\x00-\x7F]/g, "").split(""),
    tokenize: "full"
  })],
});
```

**Comment by li-zheng-hao** [comment]
> 

still not work...
![image](https://user-images.githubusercontent.com/22129824/199926086-2e6e8a67-3bbe-4b89-88f8-e4537dbd8a1d.png)
![image](https://user-images.githubusercontent.com/22129824/199926212-3d0136e9-c15a-4456-a399-fa64217faf66.png)


```js
export default defineConfig({
  plugins: [SearchPlugin({
    encode: str => str.replace(/[\x00-\x7F]/g, "").split(""),
    tokenize: "full"
  })],
});
```

**Comment by emersonbottero** [comment]
Can you share the repo again plz?

**Comment by emersonbottero** [comment]
I'll take a look.. 
If I can't managed I'll ask some of the vitepress dev that know chinese to help me.

**Comment by emersonbottero** [comment]
plz, try 
```js
 SearchPlugin({
      encode: false,
      tokenize: function (str) {
        return str.replace(/[\x00-\x7F]/g, "").split("");
      },
      filter:
        "的 一 不 在 人 有 是 为 以 于 上 他 而 后 之 来 及 了 因 下 可 到 由 这 与 也 此 但 并 个 其 已 无 小 我 们 起 最 再 今 去 好 只 又 或 很 亦 某 把 那 你 乃 它 吧 被 比 别 趁 当 从 到 得 打 凡 儿 尔 该 各 给 跟 和 何 还 即 几 既 看 据 距 靠 啦 了 另 么 每 们 嘛 拿 哪 那 您 凭 且 却 让 仍 啥 如 若 使 谁 虽 随 同 所 她 哇 嗡 往 哪 些 向 沿 哟 用 于 咱 则 怎 曾 至 致 着 诸 自".split(
          " "
        ),
    }),
```
if the filter does not make sense you can remove

**Comment by li-zheng-hao** [comment]
```js
export default defineConfig({
  plugins: [SearchPlugin({
    encode: false,
    tokenize: function (str) {
      return str.replace(/[\x00-\x7F]/g, "").split("");
    },
    // filter:
    //   "的 一 不 在 人 有 是 为 以 于 上 他 而 后 之 来 及 了 因 下 可 到 由 这 与 也 此 但 并 个 其 已 无 小 我 们 起 最 再 今 去 好 只 又 或 很 亦 某 把 那 你 乃 它 吧 被 比 别 趁 当 从 到 得 打 凡 儿 尔 该 各 给 跟 和 何 还 即 几 既 看 据 距 靠 啦 了 另 么 每 们 嘛 拿 哪 那 您 凭 且 却 让 仍 啥 如 若 使 谁 虽 随 同 所 她 哇 嗡 往 哪 些 向 沿 哟 用 于 咱 则 怎 曾 至 致 着 诸 自".split(
    //     " "
    //   ),
  })],
});
```

i tried this ,`filter` is not work , and i can only search the whole words , one word is not work, like this:
![image](https://user-images.githubusercontent.com/22129824/200093504-b3136a75-eed4-468e-ad74-75b95ba85325.png)
![image](https://user-images.githubusercontent.com/22129824/200093508-033b4077-5dbf-43fc-9fd9-005a7e6d153c.png)

**Comment by Charles7c** [comment]
你把 `模` 加进去应该就好了。[狗头]

**Comment by li-zheng-hao** [comment]
> 你把 `模` 加进去应该就好了。[狗头]

总不能写了啥我还得手动加一下吧哈哈哈

**Comment by emersonbottero** [comment]
all that this does 
 return str.replace(/[\x00-\x7F]/g, "").split("");
 is remove non chinese caractheres..

**Comment by emersonbottero** [comment]
tokenize: "full" should return a lot of results.
@li-zheng-hao could you try only with that setting?

Is really hard for me to debug because because I don't know chinese.
@Charles7c 
could you list the term you are search and what return is expected?
don't past only images.. 
I need the to be able to copy the words to test.. 😁

**Comment by li-zheng-hao** [comment]
wow! it works!!!!

![image](https://user-images.githubusercontent.com/22129824/200150912-f66e9b3a-515a-4645-8022-58a4106daca2.png)
![image](https://user-images.githubusercontent.com/22129824/200150916-7d3184c0-1797-4005-8fb2-4d07335e19cd.png)
![image](https://user-images.githubusercontent.com/22129824/200150917-4c455535-5f06-4df9-a6f5-9a6878760e0a.png)


```js
export default defineConfig({
  plugins: [SearchPlugin({
    encode: false,
    tokenize: "full"
  })],
});
```

enter `单`、`单元`、`单元测试` will list `单元测试` (means unit test 😁)

**Comment by ForeverSun** [comment]
nb



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 6, 2022 10:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [emersonbottero/vitepress-plugin-search] I Can`t search forChinese (Issue #11)




 
wow! it works!!!!
 

 
 
 export default defineConfig({   plugins: [SearchPlugin({     encode: false,     tokenize: "full"   })], });
 
enter 单、单元、单元测试 will list 单元测试 (means unit test 😁)

**Comment by Charles7c** [comment]
> tokenize: "full" should return a lot of results. @li-zheng-hao could you try only with that setting?
> 
> Is really hard for me to debug because I don't know chinese. @Charles7c could you list the term you are search and what return is expected? don't past only images.. I need the to be able to copy the words to test.. 😁

thanks a lot. @emersonbottero , as configured for the @li-zheng-hao test, it worked. 😁

``` ts
import { defineConfig } from 'vite'
import { SearchPlugin } from 'vitepress-plugin-search'

export default defineConfig({
  plugins: [
    SearchPlugin({
      encode: false,
      tokenize: 'full'
    })
  ]
})
```

**Comment by emersonbottero** [comment]
Uhuuuu 🎉

**Comment by arcqiufeng** [comment]
> > tokenize: "full" should return a lot of results. @li-zheng-hao could you try only with that setting?
> > Is really hard for me to debug because I don't know chinese. @Charles7c could you list the term you are search and what return is expected? don't past only images.. I need the to be able to copy the words to test.. 😁
> 
> thanks a lot. @emersonbottero , as configured for the @li-zheng-hao test, it worked. 😁
> 
> ```ts
> // vite.config.ts
> import { defineConfig } from 'vite'
> import { SearchPlugin } from 'vitepress-plugin-search'
> 
> export default defineConfig({
>   plugins: [
>     SearchPlugin({
>       encode: false,
>       tokenize: 'full'
>     })
>   ]
> })
> ```

It works for me now. Thank you @emersonbottero @Charles7c @li-zheng-hao 

奇怪，不知道为什么一开始没有搜到这个贴子。感谢。

**Comment by arcqiufeng** [comment]
tokenize: 'full'
Then the index file is really huge. Now I have a size of 80M+ index file. (82.2 MB)

**Comment by emersonbottero** [comment]
You can try forward.
It should reduce a Lot the size If you reais chinese from left to right

**Comment by arcqiufeng** [comment]
> You can try forward. It should reduce a Lot the size If you reais chinese from left to right

Thanks for your reply.

If I change tokenize to "forward". That will reduce the count of results. I can only find the results that the search word located on the start of the whole sentence.

I think it is because of CJK language words are not divided by space but by Semantics.

**Comment by arcqiufeng** [comment]
Finally, I think I got the solution.

I found a word splitter for Chinese text: https://github.com/leizongmin/node-segment

however, I have to split the key word by space manually is searchbox in the nav bar. Else I will get nothing if the two words in searchbox is not separated by space.

Now the size of index file is reduced to 1,662Kb

83M+ -> 1.6M.

If I change the tokenizer to "full". It will be about 2M+.

```ts
// docs/vite.config.ts

import { SearchPlugin } from "vitepress-plugin-search";
import { defineConfig } from "vite";

// 分词器来源
// https://wenjiangs.com/article/segment.html
// https://github.com/leizongmin/node-segment
// 安装：
// yarn add segment -D
// 以下为样例

// 载入模块
var Segment = require('segment');
// 创建实例
var segment = new Segment();
// 使用默认的识别模块及字典，载入字典文件需要1秒，仅初始化时执行一次即可
segment.useDefault();
// 开始分词
// console.log(segment.doSegment('这是一个基于Node.js的中文分词模块。'));

var options = {

  // 采用分词器优化，
  encode: function (str) {
    return segment.doSegment(str, {simple: true});
  },
  tokenize: "forward", // 解决汉字搜索问题。来源：https://github.com/emersonbottero/vitepress-plugin-search/issues/11

  // 以下代码返回完美的结果，但内存与空间消耗巨大，索引文件达到80M+
  // encode: false,
  // tokenize: "full",

};

export default defineConfig({
  plugins: [SearchPlugin(options)],
});
```

**Comment by beierzhijin** [comment]
> Finally, I think I got the solution.
> 
> I found a word splitter for Chinese text: https://github.com/leizongmin/node-segment
> 
> I installed it: `yarn add segment -D`
> 
> however, I have to split the key words by space manually in searchbox that in the nav bar. Else I will get nothing if the two words in searchbox is not separated by space. (Can it be auto?)
> 
> Now the size of index file is reduced to 1,662Kb
> 
> 83M+ -> 1.6M. Really great progress.
> 
> If I change the tokenizer to "full". It will be about 2,581Kb.
> 
> ```ts
> // docs/vite.config.ts
> 
> import { SearchPlugin } from "vitepress-plugin-search";
> import { defineConfig } from "vite";
> 
> // 分词器来源
> // https://wenjiangs.com/article/segment.html
> // https://github.com/leizongmin/node-segment
> // 安装：
> // yarn add segment -D
> // 以下为样例
> 
> // 载入模块
> var Segment = require('segment');
> // 创建实例
> var segment = new Segment();
> // 使用默认的识别模块及字典，载入字典文件需要1秒，仅初始化时执行一次即可
> segment.useDefault();
> // 开始分词
> // console.log(segment.doSegment('这是一个基于Node.js的中文分词模块。'));
> 
> var options = {
> 
>   // 采用分词器优化，
>   encode: function (str) {
>     return segment.doSegment(str, {simple: true});
>   },
>   tokenize: "forward", // 解决汉字搜索问题。来源：https://github.com/emersonbottero/vitepress-plugin-search/issues/11
> 
>   // 以下代码返回完美的结果，但内存与空间消耗巨大，索引文件达到80M+
>   // encode: false,
>   // tokenize: "full",
> 
> };
> 
> export default defineConfig({
>   plugins: [SearchPlugin(options)],
> });
> ```

当vitepress里存在base设置时，https://beierzhijin.github.io/developer-guide/，就是这个`/developer-guide/`，https://vitepress.vuejs.org/reference/site-config#base，部署到github page，搜索后回车base会丢失导致404，本地跑没有这种情况

**Comment by zkrisj** [comment]
> Finally, I think I got the solution.
> 
> I found a word splitter for Chinese text: https://github.com/leizongmin/node-segment
> 
> I installed it: `yarn add segment -D`
> 
> however, I have to split the key words by space manually in searchbox that in the nav bar. Else I will get nothing if the two words in searchbox is not separated by space. (Can it be auto?)
> 
> Now the size of index file is reduced to 1,662Kb
> 
> 83M+ -> 1.6M. Really great progress.
> 
> If I change the tokenizer to "full". It will be about 2,581Kb.
> 
> ```ts
> // docs/vite.config.ts
> 
> import { SearchPlugin } from "vitepress-plugin-search";
> import { defineConfig } from "vite";
> 
> // 分词器来源
> // https://wenjiangs.com/article/segment.html
> // https://github.com/leizongmin/node-segment
> // 安装：
> // yarn add segment -D
> // 以下为样例
> 
> // 载入模块
> var Segment = require('segment');
> // 创建实例
> var segment = new Segment();
> // 使用默认的识别模块及字典，载入字典文件需要1秒，仅初始化时执行一次即可
> segment.useDefault();
> // 开始分词
> // console.log(segment.doSegment('这是一个基于Node.js的中文分词模块。'));
> 
> var options = {
> 
>   // 采用分词器优化，
>   encode: function (str) {
>     return segment.doSegment(str, {simple: true});
>   },
>   tokenize: "forward", // 解决汉字搜索问题。来源：https://github.com/emersonbottero/vitepress-plugin-search/issues/11
> 
>   // 以下代码返回完美的结果，但内存与空间消耗巨大，索引文件达到80M+
>   // encode: false,
>   // tokenize: "full",
> 
> };
> 
> export default defineConfig({
>   plugins: [SearchPlugin(options)],
> });
> ```

请问，只能搜索文章中的包含的标题名称，而不能搜索文章名称吗？
Can only search for the title names included in the article, not the article name
