### ISSUE TITLE
How do I configure Vitepress-plugin-search?

### ISSUE THREAD

**Issue by Charles7c** [emersonbottero/vitepress-plugin-search#17]
Now, if I want to change the default configuration, do I do it this way?

```ts
import { defineConfig } from 'vite'
import { SearchPlugin } from 'vitepress-plugin-search'

export default defineConfig({
  plugins: [
    SearchPlugin({
      //Add a wildcard at the end of the search
      wildcard: false,
      //The length of the result search preview item
      previewLength: 62,
    })
  ]
})
```

In addition, I have two small suggestions:
1.Can local search not work after I configure Algolia?
2.Can the local search style be optimized to be more similar to Algolia, so that it is insensitive when switching between Algolia and 'vitepress-plugin-search'?

![image](https://user-images.githubusercontent.com/25446948/193440061-7da5500f-6360-4a04-ad2c-77442b64bac4.png)
![image](https://user-images.githubusercontent.com/25446948/193440086-35a3b175-5e2a-4253-89c4-085a8d8b3ea2.png)

**Comment by fyzhu** [comment]
Is your problem solved?
how to use this plugin?
