### ISSUE TITLE
Possibility to search also in h2 headers

### ISSUE THREAD

**Issue by PeterPetrik** [emersonbottero/vitepress-plugin-search#18]
Would it be possible to search also in the h2 headers? I tried the plugin and it does great job looking in page title + content, but not in the headers itself.

**Comment by emersonbottero** [comment]
I'm changing the internal library used in this plugin and I'll add this also.
Will leave It open until donne.

**Comment by emersonbottero** [comment]
Hi @PeterPetrik , could you try the last version?

**Comment by PeterPetrik** [comment]
Hi, unfortuntaly we are not yet using vitepress, waiting for the public release (we are still on vuepress1). Once we migrate, I will give it a try. 

Nevertheless thanks for the fix

**Comment by pdanpdan** [comment]
To add on this, can you please change the parser to process levels 2-6 (to match h2-h6)
It needs a `#{2,6}` in
https://github.com/emersonbottero/vitepress-plugin-search/blob/74c5dda95db1a157353e732ea55fadee3bd86164/src/docs-builder.ts#L90
Maybe make it configurable from options?

**Comment by emersonbottero** [comment]
h3 to h6 dont use anchors.. I guess we can configure It in the vitepress , I'll take a look and see How It Works and then Sync It in the search results

**Comment by emersonbottero** [comment]
@pdanpdan , would it make sense to follow the level option as described in [markdown-it](https://github.com/valeriangalliat/markdown-it-anchor/blob/master/README.md)

**Comment by pdanpdan** [comment]
Yes :)

**Comment by emersonbottero** [comment]
@PeterPetrik couldn't use the level options nothing changed..
could you try and confirm? If you also can't use it plz open a an issue in the vitepress repo.

**Comment by PeterPetrik** [comment]
Tested, it searches now in h2.
