### ISSUE TITLE
problem with resolve.alias

### ISSUE THREAD

**Issue by iqorex** [emersonbottero/vitepress-plugin-search#2]
Hey,

I followed the instruction but after creating index and trying to check searchbox i can still see old algolia component how can i fix this?

I am using 1.0.0-alpha4

My current `vite config`

```
import { defineConfig } from "vite";

export default defineConfig({
  resolve: {
    alias: {
      "./components/AlgoliaSearchBox.vue":
      "vitepress-plugin-search/src/Search.vue",
    },
  },
});
```

**Comment by emersonbottero** [comment]
this file should be inside docs folder, not in the root.
If this don't solve the problem you can share a repo and I can check it out.

**Comment by iqorex** [comment]
i hade this file already in my docs folder
here is my repo : https://github.com/iqorex/vitepress-demo

**Comment by emersonbottero** [comment]
You are correct, they made some changes in the last version, they also added more slots that I probably could use now.

to work as it is you can use
```js
import { defineConfig } from "vite";

export default defineConfig({
  resolve: {
    alias: {
      "./VPNavBarSearch.vue": "vitepress-plugin-search/src/Search.vue",
    },
  },
});
```

**Comment by iqorex** [comment]
thanks it works like a charm

**Comment by iqorex** [comment]
thanks it works like a charm
