### ISSUE TITLE
Search results should not also contain custom anchors

### ISSUE THREAD

**Issue by ForeverSun** [emersonbottero/vitepress-plugin-search#21]
![image](https://user-images.githubusercontent.com/10215382/200269943-b178bbd1-2a02-4df5-91fd-20c19315825b.png)

![image](https://user-images.githubusercontent.com/10215382/200269490-88bdb7dc-9fb8-4f18-9174-e659f1dd6c8d.png)
The right thing is‘ http://localhost:5173/config/server -options.html#server-fs-strict’

**Comment by Dpeish** [comment]
Yes, I have the same problem...
![image](https://user-images.githubusercontent.com/19512105/200716725-27dd3a8c-0eeb-4f22-8033-4f0ca13ac871.png)
h2 v1.0.3  ---> vitepress generates v1-0-3;
The search node is v1.0.1

![image](https://user-images.githubusercontent.com/19512105/200717113-40701f9c-1aba-4386-af0e-dab3641bebe0.png)


As a result, the document content cannot be located...

**Comment by IsLand-x** [comment]
Are there any solutions?
