### ISSUE TITLE
Invalid hashes from parsed md files

### ISSUE THREAD

**Issue by pdanpdan** [emersonbottero/vitepress-plugin-search#22]
Hello.

It looks like in here only spaces are converted to dashes, but vitepress also removes a lot of not alphanumeric chars:
https://github.com/emersonbottero/vitepress-plugin-search/blob/74c5dda95db1a157353e732ea55fadee3bd86164/src/Search.vue#L44

```javascript
link = link.split(" ").join("-");
```
can be replaced with
```javascript
link = link.split( "#" );
link = link[0] + (typeof link[1] === "string" ? '#' + link[1].split(" ").join("-").split(/[^a-z0-9_-]+/i).join("") : "");
```

**Comment by IsLand-x** [comment]
Maybe it will be better if the markdown-it options and flexsearch options can both be configured by user.
Then you can modify the links(custom slugify) and do more custom operations

I've tried to marke a pr but unfortunately I cannot setup this project properly :(
