### ISSUE TITLE
Search CJK text

### ISSUE THREAD

**Issue by arcqiufeng** [emersonbottero/vitepress-plugin-search#24]
I tried this plugin and it worked.

But I found it cannot get all results. Sometimes it get nothing, although the words to search do exsit in the markdown file.

Is it because of searching for Chinese in the Chinese document?

**Comment by Whbbit1999** [comment]
You can see #11 .You can try to install flexsearch in your project.
It's work in my project

**Comment by arcqiufeng** [comment]
> You can see #11 .You can try to install flexsearch in your project. It's work in my project

Thanks, your suggestion solved my problem.

非常感谢。

**Comment by Whbbit1999** [comment]
不过这样改了后有一个3M左右的文件会在网站开始的时候加载
