### ISSUE TITLE
Will the plugin support The lang attribute for the search box ?

### ISSUE THREAD

**Issue by haiting** [emersonbottero/vitepress-plugin-search#27]
The plugin don't support language configuration Currently，can it be configure with a parameter like `lang` ?

```
plugins: [
     vueJsx(),
    SearchPlugin({
      encode: false,
      tokenize: 'full',
      lang: 'zh-CN'
    })
 ],
```

**Comment by haiting** [comment]
or the search box can be change by pass a slot?

**Comment by emersonbottero** [comment]
I'll try to add an labels options

**Comment by emersonbottero** [comment]
See [chinese settings for example](https://github.com/emersonbottero/vitepress-plugin-search/issues/11)
