### ISSUE TITLE
Hydration completed but contains mismatches.

### ISSUE THREAD

**Issue by laterdays** [emersonbottero/vitepress-plugin-search#29]
In a production environment

Hydration completed but contains mismatches.

**Comment by laterdays** [comment]
@emersonbottero  Looking forward to resolution

**Comment by emersonbottero** [comment]
I'll take a look. Not sure what may be causing this.

**Comment by pdanpdan** [comment]
Same as https://github.com/emersonbottero/vitepress-plugin-search/issues/23

**Comment by emersonbottero** [comment]
https://github.com/emersonbottero/vitepress-plugin-search/pull/32
