### ISSUE TITLE
Need the z-index increased

### ISSUE THREAD

**Issue by brucetp** [emersonbottero/vitepress-plugin-search#3]
It looks like the z-index needs increased to something above 20 for the modal.   The vitepress tool bar wasn't greyed out.
Also, in light mode the search item hover turns to white which isn't enough contrast.    Just FYI on both of these.   Great plugin!

Here's the modifications I made locally
```
.modal-back {
    z-index: 30;
}

.search-item:hover {
    color: var(--vp-c-brand);
}

.search-item:hover > p {
    color: var(--vp-c-brand);
}
```

**Comment by emersonbottero** [comment]
Should be fixes in the new version.. 
they changed the css in vitepress (is in alpha so they can.. 😁)
