### ISSUE TITLE
can filter Frontmatter ？

### ISSUE THREAD

**Issue by holynewbie** [emersonbottero/vitepress-plugin-search#42]
vitepress support [Frontmatter](https://vitepress.vuejs.org/guide/frontmatter)

when using it, search result looks strange。

for my doc.md

```
---
outline: deep
---

# Lint 规则
```

results 

![screenshot-20230113-121838](https://user-images.githubusercontent.com/8347286/212241646-51b8a2bc-8b14-4315-ad83-384e9b1fec37.png)

**Comment by emersonbottero** [comment]
fixed in https://github.com/emersonbottero/vitepress-plugin-search/pull/49
