### ISSUE TITLE
Include all markdown heading levels in index

### ISSUE THREAD

**Issue by pdanpdan** [emersonbottero/vitepress-plugin-search#47]
Can you please replace `#{2}` with `#{2,}` so that subheadings are also included in the index?

https://github.com/emersonbottero/vitepress-plugin-search/blob/80a33d0e3c34e94abb73f3491233c97d7756f924/src/docs-builder.ts#L92

**Comment by emersonbottero** [comment]
would it make sense to get the data from outline option?

not so sure would be easy to create a regex for the available options tough.

**Comment by pdanpdan** [comment]
If you can get the max depth in outline then it would work. 
But i think all headings are converted to anchors, so it would make sense to index them

**Comment by emersonbottero** [comment]
fixed in https://github.com/emersonbottero/vitepress-plugin-search/pull/49

**Comment by pdanpdan** [comment]
Working as expected, thank you :)
