### ISSUE TITLE
Indexed links are missing base when vitepress is not built with '/' base path

### ISSUE THREAD

**Issue by pdanpdan** [emersonbottero/vitepress-plugin-search#48]
The origin needs to be processed through `withBase`

`import { useData, withBase } from "vitepress";`
https://github.com/emersonbottero/vitepress-plugin-search/blob/faad6292b05428586d42dcafbe2076f64e8e330e/src/Search.vue#L3

`origin.value = window.location.origin + withBase(locale.value === 'root' ? '/' : locale.value);`
https://github.com/emersonbottero/vitepress-plugin-search/blob/faad6292b05428586d42dcafbe2076f64e8e330e/src/Search.vue#L81

Also can you please also remove the `index.html` in the end of the link?

**Comment by emersonbottero** [comment]
fixed in #49

**Comment by pdanpdan** [comment]
Working as expected (except `index.html` at the end, but that is not a problem), thank you :)
