### ISSUE TITLE
Hello, when my project is started, I will be prompted that the localePath returned in useData() is undefined, which will cause the search function to fail

### ISSUE THREAD

**Issue by 2401345934** [emersonbottero/vitepress-plugin-search#51]
Hello, when my project is started, I will be prompted that the localePath returned in useData() is undefined, which will cause the search function to fail
<img width="721" alt="image" src="https://user-images.githubusercontent.com/52618511/215964848-e0d3cd8d-5405-4417-8da2-41024c200cab.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/52618511/215964889-5f5a3a99-56f7-4691-a091-c17f097c6685.png">

**Comment by 2401345934** [comment]
1.0.4-alpha.19

**Comment by emersonbottero** [comment]
Can you  share the repo?

**Comment by emersonbottero** [comment]
update the vitepress version to the last one.
