### ISSUE TITLE
Incorrect anchor links with baseUrl

### ISSUE THREAD

**Issue by youngbeen** [emersonbottero/vitepress-plugin-search#52]
I followed the standard guide to config my `vite.config.js`. Everything is perfect except the links.
My expect: window.location.origin + baseUrl + item link
AS IS: window.location.origin + baseUrl + baseUrl + item link
Problem is link has baseUrl twice?

e.g. when `.vitepress/config.js` has a `baseUrl` config
```javascript
baseUrl: '/sub-domain/'
```
The link anchors to `${origin}/sub-domain/sub-domain/some-document`

**Comment by emersonbottero** [comment]
can you share a repo?

**Comment by zqy233** [comment]
vitepress`^1.0.0-alpha.31`  has this problem，^1.0.0-alpha.45`  works well

**Comment by pdanpdan** [comment]
There were changes in vitepress - please use a recent version as the internals of vitepress changed (it is no longer sending the path including baseUrl)
https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md - alpha.42
