### ISSUE TITLE
Cannot find name 'flexSearchIndexOptions' and conflicts with the site theme configuration

### ISSUE THREAD

**Issue by ChengSiXi24** [emersonbottero/vitepress-plugin-search#53]
Because the error information is too long, I uploaded the error picture. I don't know why. Maybe the problem is caused by another module.

![errorphoto](https://user-images.githubusercontent.com/109007961/216829373-7794acb8-2b94-4f48-ad44-f6d0e27713a2.png)

[Link](https://github.com/ChengSiXi24/vitepress-plugin-search-bug-report-main)

**Comment by ChengSiXi24** [comment]
![image](https://user-images.githubusercontent.com/109007961/216829879-7622438c-bfbf-4a6d-8ff2-921fbfc98fde.png)

**Comment by emersonbottero** [comment]
You should create your own options object 
If you want to use with default values just don't pass Any parameter to it.
commenting line 7 should make it work

**Comment by ChengSiXi24** [comment]
感谢!您的邮件已由系统接收并保存在希酱的收件箱思い出の中で、いつも瞬間があって、かつてのことを暖めることができます。回忆中，总有些瞬间，能温暖整个曾经。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by ChengSiXi24** [comment]
Thanks for your reply. It's already late here. I will try this method and reply to you tomorrow. Thanks for your reply.

**Comment by ChengSiXi24** [comment]
An error occurred when configuring vitepress again.
![errorphoto-2-3](https://user-images.githubusercontent.com/109007961/216860634-71b5a4c7-21b2-4f49-98fe-79cb76e1802c.png)
![errorphoto-2-2](https://user-images.githubusercontent.com/109007961/216860643-6adac0d9-6071-4d26-b5ac-b9fdb37cea04.png)

[Link](https://github.com/ChengSiXi24/vitepress-plugin-search-bug-report-main)

**Comment by ChengSiXi24** [comment]
Vscode's git tool is configured to be private by default when uploaded and now has access to my repository.

**Comment by emersonbottero** [comment]
Remove the options..
SearchPlugin()

**Comment by ChengSiXi24** [comment]
Your reply has been automatically replied by the email manager, which means that the email has been received, but it may take some time for me to receive the message, because I may be early or late in China, or I may be sleeping?---This is an automatic reply from QQ mail

**Comment by ChengSiXi24** [comment]
![errorphoto-2-5](https://user-images.githubusercontent.com/109007961/216877041-37725752-4fff-46dd-be73-13719c26c514.png)
There's nothing in the <div class="app">
![image](https://user-images.githubusercontent.com/109007961/216877291-07b31ff1-f293-4955-8850-4ea3798520f8.png)
![image](https://user-images.githubusercontent.com/109007961/216877377-40fe3ce1-d043-4155-93b9-9bc7304eee07.png)

**Comment by emersonbottero** [comment]
leave only the config.js file inside .vitepress
remove node_modules and package-lock.json
npm i
npm run docs:dev
