### ISSUE TITLE
Already installed plugin and configured it in cofig.js, but no Search Bar appears in website after running 'yarn docs:dev' 

### ISSUE THREAD

**Issue by fun-enterprises** [emersonbottero/vitepress-plugin-search#54]
Hello,

As described in title of this issue, I see no Search Bar appearing in the page. 

I believe I followed the instructions correctly. Can you help me identify in what is it that I am failing?

Screenshots:
<img width="1216" alt="Screen Shot 2023-02-07 at 3 48 06 PM" src="https://user-images.githubusercontent.com/124622755/217339203-3afa7f54-029d-4c6d-bfd7-260c78f84d72.png">

<img width="1728" alt="Screen Shot 2023-02-07 at 3 48 45 PM" src="https://user-images.githubusercontent.com/124622755/217339216-d1bb19d9-c858-40e2-b171-2c0b9d1fcb9d.png">

Repo: https://github.com/fun-enterprises/business

Github Pages: https://fun-enterprises.github.io/business

Thank you

**Comment by emersonbottero** [comment]
but the docs said to use it in the vite.config.js

see [demo example](https://github.com/emersonbottero/vitepress-plugin-search/blob/main/demo/docs/vite.config.ts)
you don't need the server options

**Comment by fun-enterprises** [comment]
you are correct about the name of the file, my fault.  however, I tried correcting it and it didn't work.

I am operating under this assumptions: 

- I must locate vite.config.js in the root of /doc dir
- vite.config.js and config.js are two totally different things

any hint on why it doesn't work?

I don't understand what component uses 'vite.config.js' anyway. I couldn't find that in any documentation.

thank you for your patience, I'm just starting with vitepress and vite some things are not obvious to me yet.

**Comment by fun-enterprises** [comment]
Here's what I tried :

<img width="1060" alt="Screen Shot 2023-02-07 at 9 25 29 PM" src="https://user-images.githubusercontent.com/124622755/217397437-8ba7f14e-56c0-49d2-91a4-34968dac8022.png">

**Comment by emersonbottero** [comment]
@zqy233 , your vitepress application settings is all wrong, even removing this plugin it wont run.. 
first make sure you vitepress is working.. 
the issue with your repo is inside .vitepress there should only be an config.js and nothing else
remove the theme subfolders inside of it
delete cache inside .vitepress
aldo delete node_modules and pachage-lock.json
then run
npm i 

npm run docs:dev and it should work
![image](https://user-images.githubusercontent.com/12377432/217434859-013a6a99-9995-4b72-978c-888a21c16b8a.png)

**Comment by emersonbottero** [comment]
@fun-enterprises the settings should be places in a vite.config.js file at the root of docs

![Uploading image.png…]()

**Comment by fun-enterprises** [comment]
I was able to solve my problem by doing exactly what you told me.

thank you @emersonbottero. now the search component appears in the UI.
