### ISSUE TITLE
Some titles are not included in search results

### ISSUE THREAD

**Issue by vanchKong** [emersonbottero/vitepress-plugin-search#55]
This is the chinese-translation project of vitepress.[here](https://github.com/vanchKong/VitePressCN)
u can clone and try search.
Sometimes I can't search the title (unless the content below this title contains the title itself field).
u can try that the content's not containing the title itself field, and check the result.
In fact, I checked many other projects and they all work, I wonder why I can't.
thanks!

**Comment by emersonbottero** [comment]
Please add the words you are searching here.
I can't type in Chinese and without it is really hard for me to debug

**Comment by emersonbottero** [comment]
@vanchKong  ???

**Comment by vanchKong** [comment]
sorry，vitepress provide an other  way to searching content, i forget how to recurrence issue
