### ISSUE TITLE
Add option to allow/ignore file paths matching regexes or globs

### ISSUE THREAD

**Issue by Pandapip1** [emersonbottero/vitepress-plugin-search#56]
Suggested API:

```diff
 var options = {
   ...flexSearchIndexOptions,
   previewLength: 62,
   buttonLabel: "Search",
   placeholder: "Search docs",
+  allow: [ // If present with non-zero length, file paths NOT matching one of these regexes will be discarded
+    /someregex/g
+  ],
+  ignore: [ // If present with non-zero length, file paths matching at least one of these regexes will be discarded
+    /someregex2/g
+  ],
 };
```

(If both are present, files must not match any ignore pattern AND must match an allow pattern)

**Comment by puyt** [comment]
any update? I can't use the plugin atm because it keeps finding results inside node_modules

**Comment by emersonbottero** [comment]
have you try version 19? I ignore node_modules in that version.

**Comment by puyt** [comment]
> have you try version 19? I ignore node_modules in that version.

Yes it's working with this MR, thx :+1:

**Comment by Pandapip1** [comment]
Thank you! I'll check it out.
