### ISSUE TITLE
Customise search result groups title

### ISSUE THREAD

**Issue by shadow-light** [emersonbottero/vitepress-plugin-search#63]
This plugin appears to generate search results groups from the URL of results, grouping them when they occur in the same page.

Currently it hyphenates the URL, e.g. `/parent/child/` becomes `Parent-child`. Could it instead be `Parent > Child` or customisable?

Or alternatively, could the actual title of pages be extracted and used to group results? This might add to the index size though.

**Comment by emersonbottero** [comment]
I think it only replaces spaces with -
The rest comes from file structure. I do split a page in different docs but is based on anchors.  Do you have a published page as an example of what you expected x current

**Comment by sagargurtu** [comment]
+1

Ability to customize the display labels of search groups will be really helpful ([link](https://github.com/emersonbottero/vitepress-plugin-search/blob/460a8561047cb7d561e7cfbc429088198c043562/src/Search.vue#L170)). The current auto-generated labels are unappealing and sometimes could be unnecessarily long.

<img width="559" alt="screen" src="https://user-images.githubusercontent.com/18263719/229366694-1e22bbf6-8457-47c2-96f0-ab1197bb8c7b.png">
