### ISSUE TITLE
Search does not appear if srcDir config is specified in vitepress config

### ISSUE THREAD

**Issue by adarshmadrecha** [emersonbottero/vitepress-plugin-search#73]
Better title of this issue could be _**"Support for `srcDir` config"**_

Just adding the key `srcDir` in the config will cause the Search component to disappear from the website.

```js
// file: .vitepress\config.js
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  srcDir: './book', 
  title: "My Awesome Book",   
  }
})

```

**Comment by adarshmadrecha** [comment]
This issue could be because the plugin is specifically looking only at root directory.

Ref: https://github.com/emersonbottero/vitepress-plugin-search/blob/460a8561047cb7d561e7cfbc429088198c043562/src/index.ts#L52

So, in order to support `srcDir` option, it should be modified to 
```js
 return await IndexSearch(config.base, options); 
```

**Comment by pranali98-cpu** [comment]
I am also facing this same issue.
Repo to reproduce this error: https://github.com/icaibook/audittrail

**Comment by emersonbottero** [comment]
@adarshmadrecha , @pranali98-cpu  you are doing something wrong.
the base has other function , it only has meaning after deploying the page. is used to handle subdomains.

@pranali98-cpu , your example has the wrong script, when not using the default docs you must specify the origin.

like vitepress dev book
