### ISSUE TITLE
should include package manager

### ISSUE THREAD

**Issue by userquin** [emersonbottero/vitepress-plugin-search#76]
I've pnpm 8 installed on my local, since you don't have packageManager entry in package.json the lock file is changed once installing dependencies, can you share pnpm version you're using (it seems pnpm 7)?

**Comment by emersonbottero** [comment]
I don't get it. You can use any package manager to install this plugin.

**Comment by userquin** [comment]
@emersonbottero I forked this repo, the package.json file has no "packageManager" entry, and so on my local, running `pnpm install` change the lock file. If I send a PR...

**Comment by emersonbottero** [comment]
Can't you use npm instead?

**Comment by userquin** [comment]
@emersonbottero

To fix it here, it is quite simple, run `pnpm --version` on your local, and then add `"packageManager": "pnpm@<version>"` entry.

Here some examples using pnpm 7 and 8:
- https://github.com/vuejs/vitepress/blob/main/package.json#L6 (pnpm 8)
- https://github.com/elk-zone/elk/blob/main/package.json#L5 (pnpm 7)
