### ISSUE TITLE
Are there any plans to support shortcut key operations?

### ISSUE THREAD

**Issue by LemonLzy** [emersonbottero/vitepress-plugin-search#81]
For example, when searching, use the arrows to select an option and press Enter to confirm the option.

like https://vitepress.dev/

![image](https://github.com/emersonbottero/vitepress-plugin-search/assets/32241375/185b653d-4338-4323-af39-be561fc7ca0a)

**Comment by emersonbottero** [comment]
We can do that... 
If you want you can also make an PR. 😃
