### ISSUE TITLE
error when building and deploying

### ISSUE THREAD

**Issue by Heus-Sueh** [emersonbottero/vitepress-plugin-search#83]
For some reason it stays in infinite "indexing" and doesn't come out of it, it stayed for 2 hours and nothing
![image](https://github.com/emersonbottero/vitepress-plugin-search/assets/98482469/04606d80-3a3d-425b-adbe-f5c48fd9fa9d)

This is my repository if you want to investigate:
https://github.com/c-pirataria/Megathread-V2

**Comment by emersonbottero** [comment]
vitepress has first class search now.. 
just use
```ts
 themeConfig: {
    search: {
      provider: 'local'
    }
}
```

**Comment by Heus-Sueh** [comment]
> vitepress has first class search now.. just use
> 
> ```ts
>  themeConfig: {
>     search: {
>       provider: 'local'
>     }
> }
> ```

unfortunately their search doesn't work well with my project and I don't know why

**Comment by emersonbottero** [comment]
add --- at the end of index.md than

**Comment by Heus-Sueh** [comment]
> add --- at the end of index.md than

didn't solve

**Comment by Heus-Sueh** [comment]
Wait, actually I was stupid and didn't deploy it

**Comment by Heus-Sueh** [comment]
> add --- at the end of index.md than

resolved
