### ISSUE TITLE
GitHub Releases?

### ISSUE THREAD

**Issue by Huskydog9988** [emersonbottero/vitepress-plugin-search#9]
Im honestly just looking for a quick and easy way to see whats changed between versions. If that comes in the form of a changelog, github releases, or some other solution, it would greatly help.

**Comment by emersonbottero** [comment]
I'll try to set it up in CI/CD.

New Version Publish.. 🚀

extract data directly from md files (seems fast ⚡)
It parse the anchors ⚓
It runs in dev or build (it uses the rollup hooks)
no complex setup to make it work.. just add the plugin and you are good to go.
need beta tester ⚗
Next Improvements!

use the algolia component passing [transformSearchClient](https://docsearch.algolia.com/docs/api#transformsearchclient) suggested by @mattjcowan! Can we use it @brc-dd ?
depending on the results maybe it is better to rally convert to html and then run the parser!
add options to the plugin like preview length
add page title to the search? (not sure is revelant)
exclude Frontmatter data from the index
Awesome Features (not sure if easily implemented)

Allow user to chose the indexer library (in this case we should require a parser and a reader to populate the founded items list

**Comment by brc-dd** [comment]
Yeah sorry about that. I was busy with i18n implementation. I will surely check this out in 2-3 days. Then we can discuss what all can be improved here.
